name: ri-ml-base
channels:
- conda-forge
- defaults
channel_priority: strict
dependencies:
- python=3.12
- gdal
- geopandas
- rasterio
- shapely
- fiona
- zarr
- rioxarray
- xarray
- netcdf4
- pyproj
- proj
- proj-data
- python-pdal
- pdal
- dask-geopandas
- pip
- conda-lock
- ipykernel
- pyyaml
- pip:
  - flake8>=7.0.0
  - mypy>=1.0.0
  - ruff>=0.6.0
  - black
  - pytest
  - pytest-benchmark
  - jupyterlab
  - contextily
  - xmip>=0.7.0
  - xclim>=0.50.0
  - torchvision
  - seaborn
  - cartopy
  - optuna
  - plotly
  - sentinelsat
  - hda
